### ISSUE TITLE
Make Parent.GenServer act as a supervisor to child processes

### ISSUE THREAD

**Issue by michalmuskala** [sasa1977/parent#2]
This would allow a `Parent.GenServer` to act as a supervisor and ensure proper upgrades during a hot upgrade procedure and proper termination semantics during application's supervision tree shutdown.

As far as I understand there's actually not much needed to support this:

* "fake" the `$initial_call` pdict value to refer to a function in `:supervisor` module.
* reply to a `which_children` GenServer call
* reply to a `count_children` GenServer call
* return a callback module in `format_status` (see [`DynamicSupervisor`](https://github.com/elixir-lang/elixir/blob/9de1e942f112edd8d055e91c5eef90cf7768b78f/lib/elixir/lib/dynamic_supervisor.ex#L1010))

My particular use case is a poolboy-like pool that acts nicely in a supervision tree. Poolboy starts a supervisor directly under a GenServer which might be problematic in some situations.

**Comment by sasa1977** [comment]
Thanks for the proposal!

I mostly created the original parent to support parenting of short-living processes. I didn't want to cause confusion with supervisor, so I deliberately didn't name it `GenParent` (which is in fact the name I started with in an original internal hackathon).

That said, I agree that there are cases where children are long-running workers (GenServers & friends), and plain supervisor doesn't suffice, so parent could definitely help here.

So I'm generally in favour of this idea.

I think that in addition to what you mention, we need to adapt the [default generated spec](https://github.com/sasa1977/parent/blob/ca5d8adaa0251a436bb7fac13cfa505d15ea4d5d/lib/parent/gen_server.ex#L273-L277) to use the `:supervisor` type.

I guess that to be fully supervisor compliant, a parent process should work with all the `:supervisor` interface functions, so that any code which walks the hierarchy and relies on the `:supervisor` type can work with parent processes. 

WDYT?

**Comment by michalmuskala** [comment]
Yes, I think making the process support all of `:supervisor` interface is a good idea. That said, I think only the `which_children` call and the `format_status` return are required by the release handler. There might be other things observer uses internally as well, though.

**Comment by sasa1977** [comment]
OK, I'm definitely interested in having this added to parent. 

My current feeling is that all supervisor specific code should sit in [Parent.GenServer](https://github.com/sasa1977/parent/blob/master/lib/parent/gen_server.ex). This is going to complicate things if we ever want to support other behaviours (e.g. GenStage), but I'm not sure it's worth overthinking this ATM.

I can't promise that I'll be able to do it immediately, because my schedule is somewhat full ATM. If you're interested in tackling this yourself, let me know. 

If you're gonna work on it, I'd still like to cleanup the GenServer tests first. They're currently messy, because I was playing with property tests, and did some cheap stateful emulation. While I think that property tests make sense in other areas (functional and procdict), I feel that in GenServer they're not really super helpful (at least not until we get the support for stateful tests), so I'd like to convert them to regular tests. Since that's my own mess, I think it's better if I clean it up myself :-) It shouldn't take too long, so I should be able to find some time to do it these days.

**Comment by sasa1977** [comment]
I finally found the time to work on this. The related PR is available in #5, if you want to take a look. I still need to work on docs, but I wouldn't mind a second pair of eyes taking a look at this :-) If you'll do that, you can skip the first commit (which is just some internal restructuring of tests), and start with the second commit.
